apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.community.name }}
  labels:
    app: {{ .Values.community.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.community.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.community.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.community.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.community.name }}
          image: "{{ .Values.community.image.repository }}:{{ .Values.community.image.tag }}"
          imagePullPolicy: {{ .Values.community.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.community.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.service.name }}
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.service.port }}"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}